version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/server
      - /server/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped
